version: '2'
services:
  javap_Mysql_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: javap
      MYSQL_USER: spring
      MYSQL_PASSWORD: springpw